# Generated by Django 5.2.1 on 2025-05-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'ordering': ['name']},
        ),
    ]
