# Generated by Django 5.2.1 on 2025-05-24 20:46

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_index_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexnode',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384, help_text='384 sized embedding for MniLM L6 V2.'),
        ),
    ]
