# Generated by Django 5.2.1 on 2025-05-24 21:01

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_indexnode_embedding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='indexnode',
            index=pgvector.django.indexes.HnswIndex(fields=['embedding'], name='indexnode_embedding_index', opclasses=['vector_cosine_ops']),
        ),
    ]
